dist: xenial
language: python
services:
  - docker
python:
  - '3.7'
install:
  - pip install sanic
  - pip install pyjwt
  - pip install -r requirements.txt
script:
  - python -m compileall .
deploy:
  - provider: script
    script: bash ./docker-deploy.sh
    on:
      branch: master
