dist: xenial
language: python
services:
  - docker
python:
  - '3.7'
script:
  - python -c "print('build start')"
deploy:
  - provider: script
    script: bash ./docker-deploy.sh
    on:
      branch: master
